// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLoginStatus() {
  return window['go']['main']['App']['CheckLoginStatus']();
}

export function CheckPermissions() {
  return window['go']['main']['App']['CheckPermissions']();
}

export function ClearChatUnread() {
  return window['go']['main']['App']['ClearChatUnread']();
}

export function ClearExamBrowserCache() {
  return window['go']['main']['App']['ClearExamBrowserCache']();
}

export function DownloadExamResource(arg1) {
  return window['go']['main']['App']['DownloadExamResource'](arg1);
}

export function GetChatConversations() {
  return window['go']['main']['App']['GetChatConversations']();
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChatUnread() {
  return window['go']['main']['App']['GetChatUnread']();
}

export function GetExamPaperFiles() {
  return window['go']['main']['App']['GetExamPaperFiles']();
}

export function GetExamPaperViewURL() {
  return window['go']['main']['App']['GetExamPaperViewURL']();
}

export function GetExamQuizViewURL() {
  return window['go']['main']['App']['GetExamQuizViewURL']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStudentInfo() {
  return window['go']['main']['App']['GetStudentInfo']();
}

export function HandleBeforeClose() {
  return window['go']['main']['App']['HandleBeforeClose']();
}

export function LoadExamViewFile(arg1) {
  return window['go']['main']['App']['LoadExamViewFile'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function NavigateToLogin() {
  return window['go']['main']['App']['NavigateToLogin']();
}

export function OpenBrowser(arg1) {
  return window['go']['main']['App']['OpenBrowser'](arg1);
}

export function OpenExamPaper() {
  return window['go']['main']['App']['OpenExamPaper']();
}

export function OpenExamQuiz() {
  return window['go']['main']['App']['OpenExamQuiz']();
}

export function OpenExamResource(arg1) {
  return window['go']['main']['App']['OpenExamResource'](arg1);
}

export function OpenLocationSettings() {
  return window['go']['main']['App']['OpenLocationSettings']();
}

export function ReloadExamPage() {
  return window['go']['main']['App']['ReloadExamPage']();
}

export function ReturnToDashboard() {
  return window['go']['main']['App']['ReturnToDashboard']();
}

export function SendChatMessage(arg1) {
  return window['go']['main']['App']['SendChatMessage'](arg1);
}

export function SendWebcamFrame(arg1) {
  return window['go']['main']['App']['SendWebcamFrame'](arg1);
}

export function SubmitExamWork() {
  return window['go']['main']['App']['SubmitExamWork']();
}

export function UnlockChatAudio() {
  return window['go']['main']['App']['UnlockChatAudio']();
}
