// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLoginStatus():Promise<boolean>;

export function CheckPermissions():Promise<Record<string, boolean>>;

export function ClearChatUnread():Promise<void>;

export function ClearExamBrowserCache():Promise<void>;

export function DownloadExamResource(arg1:number):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetChatConversations():Promise<Array<Record<string, any>>>;

export function GetChatMessages(arg1:number):Promise<Array<Record<string, any>>>;

export function GetChatUnread():Promise<number>;

export function GetExamPaperFiles():Promise<Record<string, any>>;

export function GetExamPaperViewURL():Promise<string>;

export function GetExamQuizViewURL():Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function GetStudentInfo():Promise<Record<string, any>>;

export function GetVersionStatus():Promise<main.versionStatus>;

export function HandleBeforeClose():Promise<boolean>;

export function LoadExamViewFile(arg1:string):Promise<Record<string, any>>;

export function Logout():Promise<void>;

export function NavigateToLogin():Promise<void>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenDownloadPage(arg1:string):Promise<void>;

export function OpenExamPaper():Promise<void>;

export function OpenExamQuiz():Promise<void>;

export function OpenExamResource(arg1:number):Promise<void>;

export function OpenLocationSettings():Promise<void>;

export function RecheckVersion():Promise<main.versionStatus>;

export function ReloadExamPage():Promise<void>;

export function ReturnToDashboard():Promise<void>;

export function SendChatMessage(arg1:string):Promise<void>;

export function SendWebcamFrame(arg1:string):Promise<void>;

export function SubmitExamWork():Promise<string>;

export function UnlockChatAudio():Promise<void>;
